### ISSUE TITLE
The supplementary documents

### ISSUE THREAD

**Issue by MasyerN** [Sepideh-Azarianpour/Race-specific-prognostic-models-for-EC#2]
This is a work that can attract extensive attention. Thanks to the efforts made by the authors. I cannot obtain these files from the download link of supplementary documents provided in the manuscript PDF. May I ask if the authors can provide other access methods?

**Comment by Sepideh-Azarianpour** [comment]
We will be happy to share once the paper is accepted. It is under review now.
